In [36]:
import pandas as pd
from IPython.core import display as ICD

dict_baseline_1 = {'batch': [1],
                   'dk_cells': [11265],
                   'training_cells': [6592],
                   'precision': [1.00],
                   'recall': [0.46],
                   'repairing_recall': [0.53],
                   'f1': [0.63],
                   'repairing_f1': [0.70],
                   'detected_errors': [435],
                   'total_errors': [509],
                   'correct_repairs': [232],
                   'total_repairs': [232],
                   'total_repairs_on_correct_cells': [0],
                   'total_repairs_on_incorrect_cells': [232]}

cols_dtype = {'batch': int,
              'dk_cells': int,
              'training_cells': int,
              'precision': float,
              'recall': float,
              'repairing_recall': float,
              'f1': float,
              'repairing_f1': float,
              'detected_errors': int,
              'total_errors': int,
              'correct_repairs': int,
              'total_repairs': int,
              'total_repairs_on_correct_cells': int,
              'total_repairs_on_incorrect_cells': int}

df_baseline_1 = pd.DataFrame.from_dict(dict_baseline_1).set_index('batch')

df_baseline_1

,dk_cells,training_cells,precision,recall,repairing_recall,f1,repairing_f1,detected_errors,total_errors,correct_repairs,total_repairs,total_repairs_on_correct_cells,total_repairs_on_incorrect_cells
batch,,,,,,,,,,,,,
1,11265,6592,1.0,0.46,0.53,0.63,0.7,435,509,232,232,0,232

In [39]:
####################################################################################################
# Results for 2 batches.
####################################################################################################

dir_name = 'hospital_2_batches'

df_2b_baseline_2 = pd.read_csv(dir_name + '/repairing_quality/baseline_2.csv',
                               sep=';',
                               index_col=0,
                               dtype=cols_dtype)

df_2b_proposal_3 = pd.read_csv(dir_name + '/repairing_quality/proposal_3.csv',
                               sep=';',
                               index_col=0,
                               dtype=cols_dtype)

df_2b_proposal_4 = pd.read_csv(dir_name + '/repairing_quality/proposal_4.csv',
                               sep=';',
                               index_col=0,
                               dtype=cols_dtype)

df_2b_proposal_5 = pd.read_csv(dir_name + '/repairing_quality/proposal_5.csv',
                               sep=';',
                               index_col=0,
                               dtype=cols_dtype)

df_2b_proposal_6 = pd.read_csv(dir_name + '/repairing_quality/proposal_6.csv',
                               sep=';',
                               index_col=0,
                               dtype=cols_dtype)

df_2b_proposal_7 = pd.read_csv(dir_name + '/repairing_quality/proposal_7.csv',
                               sep=';',
                               index_col=0,
                               dtype=cols_dtype)

df_2b_list = [df_baseline_1,
              df_2b_baseline_2,
              df_2b_proposal_3,
              df_2b_proposal_4,
              df_2b_proposal_5,
              df_2b_proposal_6,
              df_2b_proposal_7]

for df in df_2b_list:
    ICD.display(df)

,dk_cells,training_cells,precision,recall,repairing_recall,f1,repairing_f1,detected_errors,total_errors,correct_repairs,total_repairs,total_repairs_on_correct_cells,total_repairs_on_incorrect_cells
batch,,,,,,,,,,,,,
1,11265,6592,1.0,0.46,0.53,0.63,0.7,435,509,232,232,0,232

,dk_cells,training_cells,precision,recall,repairing_recall,f1,repairing_f1,detected_errors,total_errors,correct_repairs,total_repairs,repairs_on_correct_cells,repairs_on_incorrect_cells
batch,,,,,,,,,,,,,
1,5311,3656,0.966667,0.439394,0.513274,0.604167,0.670520,226,264,116,120,4.0,116.0
2,9126,8530,1.000000,0.372796,0.459627,0.543119,0.629787,322,397,148,148,0.0,148.0

,dk_cells,training_cells,precision,recall,repairing_recall,f1,repairing_f1,detected_errors,total_errors,correct_repairs,total_repairs,repairs_on_correct_cells,repairs_on_incorrect_cells
batch,,,,,,,,,,,,,
1,5311,3656,0.966667,0.439394,0.513274,0.604167,0.670520,226,264,116,120,4.0,116.0
2,9126,8530,1.000000,0.372796,0.459627,0.543119,0.629787,322,397,148,148,0.0,148.0

,dk_cells,training_cells,precision,recall,repairing_recall,f1,repairing_f1,detected_errors,total_errors,correct_repairs,total_repairs,repairs_on_correct_cells,repairs_on_incorrect_cells
batch,,,,,,,,,,,,,
1,5311,3656,0.966667,0.439394,0.513274,0.604167,0.670520,226,264,116,120,4.0,116.0
2,9126,8530,1.000000,0.372796,0.459627,0.543119,0.629787,322,397,148,148,0.0,148.0

,dk_cells,training_cells,precision,recall,repairing_recall,f1,repairing_f1,detected_errors,total_errors,correct_repairs,total_repairs,repairs_on_correct_cells,repairs_on_incorrect_cells
batch,,,,,,,,,,,,,
1,5311,3656,0.966667,0.439394,0.513274,0.604167,0.67052,226,264,116,120,4.0,116.0
2,9126,1,0.294710,0.363354,0.455253,0.533030,322.00000,397,117,117,0,117.0,NaN

,dk_cells,training_cells,precision,recall,repairing_recall,f1,repairing_f1,detected_errors,total_errors,correct_repairs,total_repairs,repairs_on_correct_cells,repairs_on_incorrect_cells
batch,,,,,,,,,,,,,
1,5311,3656,0.966667,0.439394,0.513274,0.604167,0.670520,226,264,116,120,4.0,116.0
2,9126,5556,1.000000,0.375315,0.462733,0.545788,0.632696,322,397,149,149,0.0,149.0

,dk_cells,training_cells,precision,recall,repairing_recall,f1,repairing_f1,detected_errors,total_errors,correct_repairs,total_repairs,repairs_on_correct_cells,repairs_on_incorrect_cells
batch,,,,,,,,,,,,,
1,5311,3656,0.966667,0.439394,0.513274,0.604167,0.670520,226,264,116,120,4.0,116.0
2,5292,3590,1.000000,0.493878,0.578947,0.661202,0.733333,209,245,121,121,0.0,121.0

In [40]:
####################################################################################################
# Results for 10 batches.
####################################################################################################

dir_name = 'hospital_10_batches'

df_10b_baseline_2 = pd.read_csv(dir_name + '/repairing_quality/baseline_2.csv',
                                sep=';',
                                index_col=0,
                                dtype=cols_dtype)

df_10b_proposal_3 = pd.read_csv(dir_name + '/repairing_quality/proposal_3.csv',
                                sep=';',
                                index_col=0,
                                dtype=cols_dtype)

df_10b_proposal_4 = pd.read_csv(dir_name + '/repairing_quality/proposal_4.csv',
                                sep=';',
                                index_col=0,
                                dtype=cols_dtype)

df_10b_proposal_5 = pd.read_csv(dir_name + '/repairing_quality/proposal_5.csv',
                                sep=';',
                                index_col=0,
                                dtype=cols_dtype)

df_10b_proposal_6 = pd.read_csv(dir_name + '/repairing_quality/proposal_6.csv',
                                sep=';',
                                index_col=0,
                                dtype=cols_dtype)

df_10b_proposal_7 = pd.read_csv(dir_name + '/repairing_quality/proposal_7.csv',
                                sep=';',
                                index_col=0,
                                dtype=cols_dtype)

df_10b_list = [df_baseline_1,
               df_10b_baseline_2,
               df_10b_proposal_3,
               df_10b_proposal_4,
               df_10b_proposal_5,
               df_10b_proposal_6,
               df_10b_proposal_7]

for df in df_10b_list:
    ICD.display(df)

,dk_cells,training_cells,precision,recall,repairing_recall,f1,repairing_f1,detected_errors,total_errors,correct_repairs,total_repairs,total_repairs_on_correct_cells,total_repairs_on_incorrect_cells
batch,,,,,,,,,,,,,
1,11265,6592,1.0,0.46,0.53,0.63,0.7,435,509,232,232,0,232

,dk_cells,training_cells,precision,recall,repairing_recall,f1,repairing_f1,detected_errors,total_errors,correct_repairs,total_repairs,repairs_on_correct_cells,repairs_on_incorrect_cells
batch,,,,,,,,,,,,,
1,787,1036,1.000000,0.260000,0.276596,0.412698,0.433333,47,50,13,33,0.0,13.0
2,1475,1781,1.000000,0.237500,0.279412,0.383838,0.436782,68,80,19,40,0.0,19.0
3,2571,2906,1.000000,0.132231,0.155340,0.233577,0.268908,103,121,16,26,0.0,16.0
4,3198,3955,0.150794,0.118750,0.140741,0.132867,0.145594,135,160,19,132,107.0,19.0
5,4306,4615,0.948718,0.121711,0.138060,0.215743,0.241042,268,304,37,50,0.0,39.0
6,4914,5862,1.000000,0.102484,0.120879,0.185915,0.215686,273,322,33,37,0.0,33.0
7,4901,6749,1.000000,0.115727,0.137809,0.207447,0.242236,283,337,39,50,0.0,39.0
8,5369,8732,1.000000,0.092179,0.110000,0.168798,0.198198,300,358,33,43,0.0,33.0
9,5461,10230,1.000000,0.060274,0.073333,0.113695,0.136646,300,365,22,39,0.0,22.0
10,6086,11366,1.000000,0.085714,0.104762,0.157895,0.189655,315,385,33,43,0.0,33.0

,dk_cells,training_cells,precision,recall,repairing_recall,f1,repairing_f1,detected_errors,total_errors,correct_repairs,total_repairs,repairs_on_correct_cells,repairs_on_incorrect_cells
batch,,,,,,,,,,,,,
1,787,1036,1.000000,0.260000,0.276596,0.412698,0.433333,47,50,13,33,0.0,13.0
2,1475,1781,1.000000,0.237500,0.279412,0.383838,0.436782,68,80,19,40,0.0,19.0
3,2571,2906,1.000000,0.132231,0.155340,0.233577,0.268908,103,121,16,26,0.0,16.0
4,3198,3955,0.150794,0.118750,0.140741,0.132867,0.145594,135,160,19,132,107.0,19.0
5,4306,4615,0.948718,0.121711,0.138060,0.215743,0.241042,268,304,37,50,0.0,39.0
6,4914,5862,1.000000,0.102484,0.120879,0.185915,0.215686,273,322,33,37,0.0,33.0
7,4901,6749,1.000000,0.115727,0.137809,0.207447,0.242236,283,337,39,50,0.0,39.0
8,5369,8732,1.000000,0.092179,0.110000,0.168798,0.198198,300,358,33,43,0.0,33.0
9,5461,10230,1.000000,0.060274,0.073333,0.113695,0.136646,300,365,22,39,0.0,22.0
10,6086,11366,1.000000,0.085714,0.104762,0.157895,0.189655,315,385,33,43,0.0,33.0

,dk_cells,training_cells,precision,recall,repairing_recall,f1,repairing_f1,detected_errors,total_errors,correct_repairs,total_repairs,repairs_on_correct_cells,repairs_on_incorrect_cells
batch,,,,,,,,,,,,,
1,787,1036,1.000000,0.260000,0.276596,0.412698,0.433333,47,50,13,33,0.0,13.0
2,1475,1781,1.000000,0.237500,0.279412,0.383838,0.436782,68,80,19,40,0.0,19.0
3,2571,2906,1.000000,0.132231,0.155340,0.233577,0.268908,103,121,16,26,0.0,16.0
4,3198,3955,0.149606,0.118750,0.140741,0.132404,0.145038,135,160,19,133,108.0,19.0
5,4306,4615,0.948718,0.121311,0.137546,0.215116,0.240260,269,305,37,50,0.0,39.0
6,4914,5862,1.000000,0.102167,0.120438,0.185393,0.214984,274,323,33,37,0.0,33.0
7,4901,6749,1.000000,0.115385,0.137324,0.206897,0.241486,284,338,39,50,0.0,39.0
8,5369,8732,1.000000,0.091922,0.109635,0.168367,0.197605,301,359,33,43,0.0,33.0
9,5461,10230,1.000000,0.060109,0.073090,0.113402,0.136223,301,366,22,39,0.0,22.0
10,6086,11366,1.000000,0.085492,0.104430,0.157518,0.189112,316,386,33,43,0.0,33.0

,dk_cells,training_cells,precision,recall,repairing_recall,f1,repairing_f1,detected_errors,total_errors,correct_repairs,total_repairs,repairs_on_correct_cells,repairs_on_incorrect_cells
batch,,,,,,,,,,,,,
1,787,1036,1.000000,0.260000,0.276596,0.412698,0.433333,47,50,13,33,0.0,13.0
2,1475,1781,1.000000,0.237500,0.279412,0.383838,0.436782,68,80,19,40,0.0,19.0
3,2571,2906,1.000000,0.132231,0.155340,0.233577,0.268908,103,121,16,26,0.0,16.0
4,3198,3955,0.149606,0.118750,0.140741,0.132404,0.145038,135,160,19,133,108.0,19.0
5,4306,4615,0.948718,0.121311,0.137546,0.215116,0.240260,269,305,37,50,0.0,39.0
6,4914,5862,1.000000,0.102167,0.120438,0.185393,0.214984,274,323,33,37,0.0,33.0
7,4901,6749,1.000000,0.115385,0.137324,0.206897,0.241486,284,338,39,50,0.0,39.0
8,5369,1,0.069638,0.083056,0.130208,0.153374,301.000000,359,25,35,0,25.0,NaN
9,5961,1,0.053476,0.064725,0.101523,0.121581,309.000000,374,20,37,0,20.0,NaN
10,6602,1,0.055556,0.067485,0.105263,0.126437,326.000000,396,22,32,0,22.0,NaN

,dk_cells,training_cells,precision,recall,repairing_recall,f1,repairing_f1,detected_errors,total_errors,correct_repairs,total_repairs,repairs_on_correct_cells,repairs_on_incorrect_cells
batch,,,,,,,,,,,,,
1,787,1036,1.000000,0.260000,0.276596,0.412698,0.433333,47,50,13,33,0.0,13.0
2,1475,999,1.000000,0.212500,0.250000,0.350515,0.400000,68,80,17,38,0.0,17.0
3,2620,1222,1.000000,0.260163,0.304762,0.412903,0.467153,105,123,32,42,0.0,32.0
4,2688,1594,0.131034,0.130137,0.157025,0.130584,0.142857,121,146,19,151,126.0,19.0
5,3819,1210,0.646154,0.135922,0.153285,0.224599,0.247788,274,309,42,76,14.0,51.0
6,3951,1496,0.928571,0.077381,0.112554,0.142857,0.200772,231,336,26,32,0.0,28.0
7,4376,1332,1.000000,0.086592,0.125000,0.159383,0.222222,248,358,31,42,0.0,31.0
8,4813,1625,0.930233,0.103359,0.147059,0.186047,0.253968,272,387,40,53,2.0,41.0
9,5051,1432,1.000000,0.061697,0.110092,0.116223,0.198347,218,389,24,41,0.0,24.0
10,5549,1426,1.000000,0.076167,0.133621,0.141553,0.235741,232,407,31,41,0.0,31.0

,dk_cells,training_cells,precision,recall,repairing_recall,f1,repairing_f1,detected_errors,total_errors,correct_repairs,total_repairs,repairs_on_correct_cells,repairs_on_incorrect_cells
batch,,,,,,,,,,,,,
1,787,1036,1.000000,0.260000,0.276596,0.412698,0.433333,47,50,13,33,0.0,13.0
2,744,868,1.000000,0.302326,0.382353,0.464286,0.553191,34,43,13,27,0.0,13.0
3,924,833,1.000000,0.366667,0.423077,0.536585,0.594595,52,60,22,32,0.0,22.0
4,799,1004,1.000000,0.327273,0.375000,0.493151,0.545455,48,55,18,24,0.0,18.0
5,828,1147,0.606061,0.357143,0.444444,0.449438,0.512821,45,56,20,33,13.0,20.0
6,931,910,1.000000,0.218182,0.285714,0.358209,0.444444,42,55,12,12,0.0,12.0
7,819,1134,1.000000,0.437500,0.488372,0.608696,0.656250,43,48,21,21,0.0,21.0
8,890,902,1.000000,0.500000,0.555556,0.666667,0.714286,54,60,30,30,0.0,30.0
9,758,1076,1.000000,0.550000,0.666667,0.709677,0.800000,33,40,22,22,0.0,22.0
10,659,911,1.000000,0.547619,0.638889,0.707692,0.779661,36,42,23,23,0.0,23.0

Things to do:
- Check the logs when training is skipped.
- Add a metric for the percentage representing how much of the dataset is clean.